<?php
declare(strict_types=1);

/**
 * Projekte (Startseite, /projekte/ und Detailseiten).
 * Wird vom Installer (database/seed.php) und von Migrations::v3() verwendet.
 * Apps unter /projekte/<ordner>/ werden intern verlinkt (relative URL), externe Seiten mit vollständiger URL.
 */
return [
    // --- Websites & Plattformen ---
    ['slug' => 'panzerit-de', 'title' => 'panzerit.de', 'category' => 'web', 'badge_icon' => 'briefcase', 'badge_de' => 'Web-Agentur', 'badge_en' => 'Web agency',
        'tagline_de' => 'Professionelle Webentwicklung aus Bremen. Websites, die für Sie arbeiten.', 'tagline_en' => 'Professional web development from Bremen. Websites that work for you.',
        'description_de' => '<p>Panzer IT bietet professionelle Webentwicklung im Abo-Modell mit monatlichen Festpreisen: Unternehmens-Websites, Onlineshops und Landingpages — inklusive Hosting, SSL-Zertifikat, Backups und Updates.</p>',
        'description_en' => '<p>Panzer IT offers professional web development on a subscription basis with fixed monthly prices: company websites, online shops and landing pages — including hosting, SSL certificate, backups and updates.</p>',
        'url' => 'https://panzerit.de', 'image' => 'assets/screenshots/panzerit.webp', 'year_from' => '2019', 'featured' => 1],
    ['slug' => 'bremer-community-de', 'title' => 'bremer-community.de', 'category' => 'web', 'badge_icon' => 'users', 'badge_de' => 'Community', 'badge_en' => 'Community',
        'tagline_de' => 'Soziales Netzwerk für Bremen & Umgebung. Seit 2009.', 'tagline_en' => 'Social network for Bremen & surroundings. Since 2009.',
        'description_de' => '<p>Die Bremer Community ist mein Herzensprojekt: ein soziales Netzwerk für Bremen und Umgebung — seit 2009 online und mehrfach von Grund auf neu gebaut.</p>',
        'description_en' => '<p>The Bremer Community is my passion project: a social network for Bremen and the surrounding area — online since 2009 and rebuilt from scratch several times.</p>',
        'url' => 'https://bremer-community.de', 'image' => 'assets/screenshots/bremer-community.webp', 'year_from' => '2009', 'featured' => 1],
    ['slug' => 'bc24-org', 'title' => 'bc24.org', 'category' => 'web', 'badge_icon' => 'book-open', 'badge_de' => 'Affiliate & DIY', 'badge_en' => 'Affiliate & DIY',
        'tagline_de' => 'Plattform für Wachstum & Erfolg. Große Auswahl an Produkten und Anleitungen.', 'tagline_en' => 'Platform for growth & success. Wide range of products and guides.',
        'url' => 'https://bc24.org', 'image' => 'assets/screenshots/bc24.webp', 'year_from' => '2014', 'featured' => 1],
    ['slug' => 'foto18-de', 'title' => 'foto18.de', 'category' => 'web', 'badge_icon' => 'camera', 'badge_de' => 'Foto-Hosting', 'badge_en' => 'Photo hosting',
        'tagline_de' => 'Professionelle Foto-Sharing-Plattform. 12.000+ Nutzer, 2,8 Mio. Fotos.', 'tagline_en' => 'Professional photo sharing platform. 12,000+ users, 2.8M photos.',
        'url' => 'https://foto18.de', 'image' => 'assets/screenshots/foto18.webp', 'year_from' => '2015', 'meta_de' => '12.000+ Nutzer · 2,8 Mio. Fotos', 'meta_en' => '12,000+ users · 2.8M photos', 'featured' => 1],
    ['slug' => 'fotohimmel-de', 'title' => 'fotohimmel.de', 'category' => 'web', 'badge_icon' => 'cloud', 'badge_de' => 'Cloud-Speicher', 'badge_en' => 'Cloud storage',
        'tagline_de' => 'Automatische Foto & Video Cloud. Pläne ab 6,99 €/Monat.', 'tagline_en' => 'Automatic photo & video cloud. Plans from €6.99/month.',
        'url' => 'https://fotohimmel.de', 'image' => '', 'featured' => 1],
    ['slug' => 'hb3d-de', 'title' => 'hb3d.de', 'category' => 'shop', 'badge_icon' => 'shopping-cart', 'badge_de' => 'Online-Shop', 'badge_en' => 'Online shop',
        'tagline_de' => 'Online-Shop mit diversen Produkten — darunter Großmarkt-Waren für Privatpersonen.', 'tagline_en' => 'Online shop with various products — including wholesale goods for private customers.',
        'url' => 'https://hb3d.de', 'image' => 'assets/screenshots/hb3d.webp', 'featured' => 1],
    ['slug' => 'okurs-de', 'title' => 'okurs.de', 'category' => 'web', 'badge_icon' => 'graduation-cap', 'badge_de' => 'Online-Kurs', 'badge_en' => 'Online course',
        'tagline_de' => 'Online-Mathe-Kurs — Mathematik endlich verstehen.', 'tagline_en' => 'Online math course — finally understand mathematics.',
        'description_de' => '<p>Ein Online-Mathe-Kurs, den ich selbst als Schüler gebraucht hätte.</p>', 'description_en' => '<p>An online math course I would have needed myself as a student.</p>',
        'url' => 'https://okurs.de', 'image' => 'assets/screenshots/okurs.webp', 'meta_de' => '4,8★ · 2.400+ Teilnehmer', 'meta_en' => '4.8★ · 2,400+ students', 'featured' => 1],

    // --- Spiele ---
    ['slug' => 'territoriumskrieg', 'title' => 'PanzerIT Territoriumskrieg', 'category' => 'game', 'badge_icon' => 'swords', 'badge_de' => 'Strategie-Spiel', 'badge_en' => 'Strategy game',
        'tagline_de' => 'Kämpfe um Territorien auf der Hex-Karte — direkt im Browser, ohne Download.', 'tagline_en' => 'Fight for territories on the hex map — right in the browser, no download.',
        'description_de' => '<p>PanzerIT Territoriumskrieg ist ein Browser-Strategiespiel auf einer Hex-Karte. Du registrierst dich, wählst deine Spielerfarbe und kämpfst um Territorien. Eine Spielanleitung erklärt die Regeln.</p>',
        'description_en' => '<p>PanzerIT Territoriumskrieg is a browser strategy game on a hex map. Register, pick your player colour and fight for territories. A game guide explains the rules.</p>',
        'url' => 'https://panzerit.de/spiel', 'image' => '', 'meta_de' => 'Hex-Karte · Registrierung nötig', 'meta_en' => 'Hex map · registration required', 'featured' => 1],
    ['slug' => 'bremer-miner', 'title' => 'Bremer Miner', 'category' => 'game', 'badge_icon' => 'pickaxe', 'badge_de' => 'Clicker-Spiel', 'badge_en' => 'Clicker game',
        'tagline_de' => 'Clicker-Spiel mit Bremer Flair. Grabe, sammle, werde reich.', 'tagline_en' => 'A clicker game with a Bremen feel. Dig, collect, get rich.',
        'description_de' => '<p>Ein Mining-Clicker: Werte Minenschächte, Aufzug und Lagerhaus mit Münzen auf und sammle Einnahmen pro Sekunde. Im Lagerhaus arbeiten Arbeiter mit eigener Umwandlungsrate.</p><p>Mit dem Prestige setzt du deine Mine zurück und erhältst einen dauerhaften Multiplikator; Manager bleiben dabei erhalten.</p>',
        'description_en' => '<p>A mining clicker: upgrade mine shafts, elevator and warehouse with coins and earn income per second. Workers in the warehouse convert at their own rate.</p><p>With prestige you reset your mine and gain a permanent multiplier; managers are kept.</p>',
        'url' => '/projekte/bremer-miner/', 'image' => '', 'meta_de' => 'Mit Prestige-System', 'meta_en' => 'With prestige system', 'featured' => 1],
    ['slug' => 'franks-kaesekaestchen', 'title' => 'Käsekästchen', 'category' => 'game', 'badge_icon' => 'dices', 'badge_de' => 'Multiplayer-Spiel', 'badge_en' => 'Multiplayer game',
        'tagline_de' => 'Das bunte Multiplayer-Punktspiel — spiele gegen andere Spieler weltweit!', 'tagline_en' => 'The colourful multiplayer dots & boxes game — play against players worldwide!',
        'description_de' => '<p>Franks Käsekästchen ist das klassische Punktspiel als Online-Multiplayer: kostenlos registrieren, anmelden und gegen andere Spieler antreten.</p>',
        'description_en' => '<p>Franks Käsekästchen is the classic dots and boxes game as an online multiplayer: register for free, sign in and play against other players.</p>',
        'url' => '/projekte/franks-kaesekaestchen/', 'image' => '', 'meta_de' => 'Kostenlos · Multiplayer', 'meta_en' => 'Free · multiplayer', 'featured' => 1],
    ['slug' => 'spielearena', 'title' => 'Spielearena', 'category' => 'game', 'badge_icon' => 'swords', 'badge_de' => 'Multiplayer-Lobby', 'badge_en' => 'Multiplayer lobby',
        'tagline_de' => 'Schach, Dame, Poker, Mau-Mau und mehr — in Echtzeit gegen echte Gegner, mit Chat, Statistiken und Bestenliste.',
        'tagline_en' => 'Chess, checkers, poker, Mau-Mau and more — in real time against real opponents, with chat, stats and leaderboard.',
        'description_de' => '<p>Die Spielearena ist eine Lobby für Brett- und Kartenspiele in Echtzeit. Du eröffnest einen Tisch oder setzt dich an einen offenen Tisch — das Spiel startet, sobald er voll ist.</p><ul><li>8 Spiele: Schach, Dame, Vier gewinnt, Reversi, Tic-Tac-Toe, Mau-Mau, 21 und Poker (Texas Hold\'em No Limit)</li><li>Chat, Statistiken und Top-10-Bestenliste</li><li>Anzeige, wie viele Spieler online sind</li></ul>',
        'description_en' => '<p>Spielearena is a lobby for board and card games in real time. Open a table or join an open one — the game starts as soon as it is full.</p><ul><li>8 games: chess, checkers, connect four, reversi, tic-tac-toe, Mau-Mau, 21 and poker (Texas Hold\'em no limit)</li><li>Chat, statistics and top-10 leaderboard</li><li>Live count of players online</li></ul>',
        'url' => '/projekte/spiele/', 'image' => '', 'meta_de' => '8 Spiele', 'meta_en' => '8 games', 'featured' => 1],
    ['slug' => 'weltenentdecker', 'title' => 'Weltenentdecker', 'category' => 'game', 'badge_icon' => 'compass', 'badge_de' => 'GPS-Entdecker-Spiel', 'badge_en' => 'GPS explorer game',
        'tagline_de' => 'Erkunde die echte Welt, sammle digitale Stempel und steige in der Bestenliste auf.',
        'tagline_en' => 'Explore the real world, collect digital stamps and climb the leaderboard.',
        'description_de' => '<p>Geh zu einem Ort, beantworte die Frage und checke per GPS ein. Richtig beantwortet gibt es Punkte und Stempel für deinen Reisepass.</p><ul><li>Orte entdecken und per GPS einchecken</li><li>Quizfrage pro Ort</li><li>Mein Reisepass mit Stempeln und Check-in-Verlauf</li><li>Bestenliste der Entdecker</li></ul>',
        'description_en' => '<p>Go to a place, answer the question and check in via GPS. Correct answers earn points and stamps for your passport.</p><ul><li>Discover places and check in via GPS</li><li>One quiz question per place</li><li>My passport with stamps and check-in history</li><li>Explorer leaderboard</li></ul>',
        'url' => '/projekte/weltenentdecker/', 'image' => '', 'meta_de' => 'GPS · Quiz · Bestenliste', 'meta_en' => 'GPS · quiz · leaderboard', 'featured' => 1],

    // --- Shops & Deals ---
    ['slug' => 'techdeals24', 'title' => 'TechDeals24', 'category' => 'shop', 'badge_icon' => 'tag', 'badge_de' => 'Deal-Portal', 'badge_en' => 'Deal portal',
        'tagline_de' => '61.000+ MediaMarkt-Angebote täglich aktualisiert — TVs, Smartphones, Laptops, Gaming und mehr.',
        'tagline_en' => '61,000+ MediaMarkt deals updated daily — TVs, smartphones, laptops, gaming and more.',
        'description_de' => '<p>TechDeals24 zeigt über 61.000 Produkte aus dem MediaMarkt-Sortiment in 14 Kategorien, täglich aktualisiert. Sortierung nach Relevanz, Preis, Rabatt oder Name; der Kauf erfolgt direkt im MediaMarkt-Onlineshop.</p>',
        'description_en' => '<p>TechDeals24 lists more than 61,000 products from the MediaMarkt range in 14 categories, updated daily. Sort by relevance, price, discount or name; you buy directly in the MediaMarkt online shop.</p>',
        'url' => '/projekte/tech-deals-24/', 'image' => '', 'meta_de' => '61.000+ Produkte', 'meta_en' => '61,000+ products', 'featured' => 1],

    // --- Tools & Apps ---
    ['slug' => 'tarif-finder', 'title' => 'Tarif-Finder', 'category' => 'tool', 'badge_icon' => 'search', 'badge_de' => 'Vergleichsportal', 'badge_en' => 'Comparison portal',
        'tagline_de' => 'Versicherungen & Tarife kostenlos vergleichen — Kfz, Kranken, Energie, Kredite & mehr.', 'tagline_en' => 'Compare insurance & tariffs for free — car, health, energy, loans & more.',
        'description_de' => '<p>Kostenlos und unverbindlich Versicherungen und Tarife vergleichen, in Zusammenarbeit mit Tarifcheck. Die Vergleiche sind nach Themen sortiert:</p><ul><li>Kfz: Auto- und Motorradversicherung</li><li>Vorsorge: Rente, Berufsunfähigkeit, Leben, Unfall, Pflege</li><li>Kranken: private Krankenversicherung, Zusatz, Beamte, Studenten</li><li>Sach: Haftpflicht, Hausrat, Wohngebäude, Rechtsschutz, Hund</li><li>Finanzen: Kredit, Girokonto, Baufinanzierung, Kreditkarte</li><li>Energie: Solaranlage, Strom, Gas, DSL, Reisen</li></ul>',
        'description_en' => '<p>Compare insurance and tariffs for free and without obligation, powered by Tarifcheck. The comparisons are grouped by topic:</p><ul><li>Vehicles: car and motorcycle insurance</li><li>Retirement: pension, disability, life, accident, care</li><li>Health: private health insurance, supplementary, civil servants, students</li><li>Property: liability, household contents, buildings, legal protection, dog</li><li>Finance: loans, current account, mortgage, credit card</li><li>Energy: solar, electricity, gas, DSL, travel</li></ul>',
        'url' => '/projekte/tarif-finder/', 'image' => '', 'meta_de' => 'Powered by Tarifcheck', 'meta_en' => 'Powered by Tarifcheck', 'featured' => 1],
    ['slug' => 'lohnabrechnung', 'title' => 'Lohnabrechnung', 'category' => 'tool', 'badge_icon' => 'wallet', 'badge_de' => 'Einkommens-Tracker', 'badge_en' => 'Income tracker',
        'tagline_de' => 'Brutto & Netto Monat für Monat tracken — immer den Überblick über dein Einkommen.', 'tagline_en' => 'Track gross & net income month by month — always keep an eye on your earnings.',
        'description_de' => '<p>LohnTrack ist deine tägliche Lohnabrechnung: Brutto und Netto Monat für Monat erfassen und den Überblick über das eigene Einkommen behalten. Anmeldung mit E-Mail-Adresse und Passwort.</p>',
        'description_en' => '<p>LohnTrack is your daily payslip tracker: record gross and net pay month by month and keep track of your income. Sign in with e-mail address and password.</p>',
        'url' => '/projekte/lohnabrechnung/', 'image' => '', 'meta_de' => 'Mit Konto', 'meta_en' => 'Account required', 'featured' => 1],
    ['slug' => 'unendliche-geschichte', 'title' => 'Unendliche Geschichte', 'category' => 'tool', 'badge_icon' => 'pen-line', 'badge_de' => 'Kollaboratives Schreiben', 'badge_en' => 'Collaborative writing',
        'tagline_de' => 'Eine Geschichte ohne Ende — schreibe gemeinsam mit anderen an einer nie endenden Story. Rangliste, Statistiken, kostenlos.',
        'tagline_en' => 'A story without end — write together with others on a never-ending story. Leaderboard, stats, free.',
        'description_de' => '<p>Jede Besucherin und jeder Besucher schreibt an derselben Geschichte weiter — genau dort, wo der letzte Autor aufgehört hat. Wer die meisten Wörter schreibt, steigt in der Rangliste auf; Wörter, Autoren und Beiträge werden gezählt.</p>',
        'description_en' => '<p>Every visitor continues the same story — exactly where the last author stopped. Whoever writes the most words climbs the leaderboard; words, authors and contributions are counted.</p>',
        'url' => '/projekte/unendliche_geschichte/', 'image' => '', 'meta_de' => 'Kostenlos · Rangliste', 'meta_en' => 'Free · leaderboard', 'featured' => 1],
    ['slug' => 'bewerbungspilot', 'title' => 'BewerbungsPilot', 'category' => 'tool', 'badge_icon' => 'briefcase', 'badge_de' => 'Bewerbungs-App', 'badge_en' => 'Job application app',
        'tagline_de' => 'Lebenslauf hochladen, Wunschberuf angeben — passende Stellen finden und für jede Anzeige Lebenslauf und Anschreiben erstellen.',
        'tagline_en' => 'Upload your CV, name your dream job — find matching vacancies and get a tailored CV and cover letter for every ad.',
        'description_de' => '<p>BewerbungsPilot holt Stellenangebote von der Bundesagentur für Arbeit, LinkedIn, StepStone, Stellenanzeigen.de und Arbeitnow zu deinem Wunschberuf und erstellt für jede Anzeige einen passgenauen Lebenslauf und ein individuelles Anschreiben.</p><ul><li>Lebenslauf als PDF hochladen oder im Formular erstellen</li><li>Master-Vorlage nach der Google-XYZ-Formel, optimiert für Bewerbungssysteme (ATS)</li><li>Registrierung kostenlos, bezahlt wird nur pro Bewerbung</li></ul>',
        'description_en' => '<p>BewerbungsPilot pulls vacancies from the German Federal Employment Agency, LinkedIn, StepStone, Stellenanzeigen.de and Arbeitnow for your desired profession and creates a tailored CV and cover letter for each ad.</p><ul><li>Upload your CV as PDF or build it in the form</li><li>Master template based on the Google XYZ formula, optimised for applicant tracking systems (ATS)</li><li>Free registration, you only pay per application</li></ul>',
        'url' => '/projekte/bewerbungen/', 'image' => '', 'meta_de' => 'Bezahlung nur pro Bewerbung', 'meta_en' => 'Pay per application only', 'featured' => 1],
    ['slug' => 'trockenheld', 'title' => 'Trockenheld', 'category' => 'tool', 'badge_icon' => 'trophy', 'badge_de' => 'Challenge-App', 'badge_en' => 'Challenge app',
        'tagline_de' => 'Die Web-App für deine Challenge ohne Alkohol. Täglich einchecken, Streaks sammeln, Meilensteine feiern.',
        'tagline_en' => 'The web app for your alcohol-free challenge. Check in daily, collect streaks, celebrate milestones.',
        'description_de' => '<p>Trockenheld ist dein tägliches Challenge-Game: Ein Klick bestätigt, dass du nichts Alkoholisches getrunken hast — dafür gibt es Punkte, die mit jedem Tag deiner Serie steigen (Combo-Bonus), Level-Aufstiege und Boni bei Woche (+50), Monat (+250), Halbjahr (+1000) und Jahr (+3000).</p><ul><li>Täglich einchecken, Fortschritt im Logbuch mit Smileys</li><li>Streaks, Level und Punkte; ein Rückfall kostet mehr, als ein guter Tag bringt</li><li>Öffentliches Profil, um Statistiken zu zeigen</li></ul>',
        'description_en' => '<p>Trockenheld is your daily challenge game: one click confirms you did not drink anything alcoholic — earn points that grow with every day of your streak (combo bonus), level-ups and bonuses for a week (+50), month (+250), half year (+1000) and year (+3000).</p><ul><li>Check in daily, progress logged with smileys</li><li>Streaks, levels and points; a relapse costs more than a good day earns</li><li>Public profile to show your stats</li></ul>',
        'url' => '/projekte/trockenheld/', 'image' => '', 'meta_de' => 'Kostenlos starten', 'meta_en' => 'Free to start', 'featured' => 1],
    ['slug' => 'poesiealbum', 'title' => 'Franks Poesiealbum', 'category' => 'tool', 'badge_icon' => 'book-open', 'badge_de' => 'Poesiealbum', 'badge_en' => 'Autograph book',
        'tagline_de' => 'Hier sammeln sich alle Einträge von Freunden und Familie. Trag dich auch ein!',
        'tagline_en' => 'All entries from friends and family collect here. Add yours too!',
        'description_de' => '<p>Ein digitales Poesiealbum: Freunde und Familie tragen sich nach der Registrierung mit einem Eintrag ein, alle Einträge stehen auf der Übersichtsseite.</p>',
        'description_en' => '<p>A digital autograph book: friends and family register and leave an entry; all entries are shown on the overview page.</p>',
        'url' => '/projekte/poesiealbum/', 'image' => '', 'featured' => 1],

    // Private Login-Tools: standardmäßig unsichtbar — im Admin bei Bedarf sichtbar schalten
    ['slug' => 'panzer-it-cockpit', 'title' => 'Panzer IT Cockpit', 'category' => 'tool', 'badge_icon' => 'layout-dashboard', 'badge_de' => 'Internes Tool', 'badge_en' => 'Internal tool',
        'tagline_de' => 'Deine Firma an einem Ort: Tagesplan, Kunden, Briefe, Ziel, Fahrtenbuch, Steuern und Coach.',
        'tagline_en' => 'Your company in one place: daily plan, clients, letters, goals, logbook, taxes and coach.',
        'url' => '/projekte/cockpit/', 'featured' => 0, 'visible' => 0],
    ['slug' => 'social-media-manager', 'title' => 'Social Media Manager', 'category' => 'tool', 'badge_icon' => 'share-2', 'badge_de' => 'Internes Tool', 'badge_en' => 'Internal tool',
        'tagline_de' => 'Social-Media-Verwaltung von Panzer IT (Login erforderlich).', 'tagline_en' => 'Social media management by Panzer IT (login required).',
        'url' => '/projekte/social-media/', 'featured' => 0, 'visible' => 0],
];
