-- Frank Panzer – Datenbankschema (MySQL 5.7+/MariaDB 10.3+)
-- Wird vom Installer ausgeführt. Jede Anweisung endet mit ";" am Zeilenende.

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(60) NOT NULL,
  email VARCHAR(190) NOT NULL DEFAULT '',
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','editor') NOT NULL DEFAULT 'editor',
  totp_secret VARCHAR(64) NULL,
  totp_enabled TINYINT(1) NOT NULL DEFAULT 0,
  last_login DATETIME NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  skey VARCHAR(80) NOT NULL,
  svalue MEDIUMTEXT NULL,
  PRIMARY KEY (skey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_limits (
  rkey VARCHAR(140) NOT NULL,
  hits INT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (rkey),
  KEY idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sections (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  skey VARCHAR(40) NOT NULL,
  anchor VARCHAR(60) NOT NULL DEFAULT '',
  label_de VARCHAR(120) NOT NULL DEFAULT '',
  label_en VARCHAR(120) NOT NULL DEFAULT '',
  title_de VARCHAR(255) NOT NULL DEFAULT '',
  title_en VARCHAR(255) NOT NULL DEFAULT '',
  intro_de TEXT NULL,
  intro_en TEXT NULL,
  nav_de VARCHAR(60) NOT NULL DEFAULT '',
  nav_en VARCHAR(60) NOT NULL DEFAULT '',
  in_nav TINYINT(1) NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  sort INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_skey (skey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stats (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  count_to DECIMAL(12,1) NOT NULL DEFAULT 0,
  auto_years TINYINT(1) NOT NULL DEFAULT 0,
  decimals TINYINT NOT NULL DEFAULT 0,
  prefix VARCHAR(20) NOT NULL DEFAULT '',
  suffix_de VARCHAR(30) NOT NULL DEFAULT '',
  suffix_en VARCHAR(30) NOT NULL DEFAULT '',
  label_de VARCHAR(160) NOT NULL DEFAULT '',
  label_en VARCHAR(160) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS about_badges (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  text_de VARCHAR(160) NOT NULL DEFAULT '',
  text_en VARCHAR(160) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS interests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS facts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS timeline (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  year VARCHAR(20) NOT NULL DEFAULT '',
  title_de VARCHAR(200) NOT NULL DEFAULT '',
  title_en VARCHAR(200) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  accent TINYINT(1) NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(120) NOT NULL,
  title VARCHAR(160) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'web',
  badge_icon VARCHAR(60) NOT NULL DEFAULT '',
  badge_de VARCHAR(80) NOT NULL DEFAULT '',
  badge_en VARCHAR(80) NOT NULL DEFAULT '',
  tagline_de VARCHAR(400) NOT NULL DEFAULT '',
  tagline_en VARCHAR(400) NOT NULL DEFAULT '',
  description_de MEDIUMTEXT NULL,
  description_en MEDIUMTEXT NULL,
  url VARCHAR(255) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  tech VARCHAR(255) NOT NULL DEFAULT '',
  year_from VARCHAR(10) NOT NULL DEFAULT '',
  meta_de VARCHAR(160) NOT NULL DEFAULT '',
  meta_en VARCHAR(160) NOT NULL DEFAULT '',
  status ENUM('live','beta','archiv') NOT NULL DEFAULT 'live',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS former_sites (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  year VARCHAR(10) NOT NULL DEFAULT '',
  domain VARCHAR(160) NOT NULL DEFAULT '',
  text_de VARCHAR(255) NOT NULL DEFAULT '',
  text_en VARCHAR(255) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS maker_projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  status ENUM('done','planned') NOT NULL DEFAULT 'done',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS shop_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS skill_groups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS skills (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id INT UNSIGNED NOT NULL,
  name VARCHAR(80) NOT NULL,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  level TINYINT NOT NULL DEFAULT 2,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_group (group_id),
  CONSTRAINT fk_skill_group FOREIGN KEY (group_id) REFERENCES skill_groups (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cv_entries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  kind ENUM('education','experience') NOT NULL DEFAULT 'experience',
  period VARCHAR(40) NOT NULL DEFAULT '',
  title_de VARCHAR(200) NOT NULL DEFAULT '',
  title_en VARCHAR(200) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tools (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS music_genres (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  name VARCHAR(80) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tracks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  caption TEXT NULL,
  genre VARCHAR(160) NOT NULL DEFAULT '',
  platform VARCHAR(40) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL DEFAULT '',
  video_id VARCHAR(32) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  plays INT UNSIGNED NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  source VARCHAR(12) NOT NULL DEFAULT 'manual',
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_video (video_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(160) NOT NULL,
  category_de VARCHAR(80) NOT NULL DEFAULT '',
  category_en VARCHAR(80) NOT NULL DEFAULT '',
  icon VARCHAR(60) NOT NULL DEFAULT '',
  title_de VARCHAR(255) NOT NULL DEFAULT '',
  title_en VARCHAR(255) NOT NULL DEFAULT '',
  excerpt_de TEXT NULL,
  excerpt_en TEXT NULL,
  content_de MEDIUMTEXT NULL,
  content_en MEDIUMTEXT NULL,
  image VARCHAR(255) NOT NULL DEFAULT '',
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  likes INT UNSIGNED NOT NULL DEFAULT 0,
  views INT UNSIGNED NOT NULL DEFAULT 0,
  allow_comments TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_slug (slug),
  KEY idx_pub (status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  post_id INT UNSIGNED NOT NULL,
  name VARCHAR(80) NOT NULL,
  message TEXT NOT NULL,
  status ENUM('pending','approved','spam') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_post (post_id, status),
  CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faq (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  q_de VARCHAR(255) NOT NULL DEFAULT '',
  q_en VARCHAR(255) NOT NULL DEFAULT '',
  a_de TEXT NULL,
  a_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner_steps (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title_de VARCHAR(160) NOT NULL DEFAULT '',
  title_en VARCHAR(160) NOT NULL DEFAULT '',
  text_de TEXT NULL,
  text_en TEXT NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(80) NOT NULL,
  title_de VARCHAR(200) NOT NULL DEFAULT '',
  title_en VARCHAR(200) NOT NULL DEFAULT '',
  subtitle_de VARCHAR(255) NOT NULL DEFAULT '',
  subtitle_en VARCHAR(255) NOT NULL DEFAULT '',
  content_de MEDIUMTEXT NULL,
  content_en MEDIUMTEXT NULL,
  in_footer TINYINT(1) NOT NULL DEFAULT 1,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_links (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  icon VARCHAR(60) NOT NULL DEFAULT '',
  label VARCHAR(80) NOT NULL,
  handle VARCHAR(80) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL,
  in_hero TINYINT(1) NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  subject VARCHAR(200) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  kind VARCHAR(12) NOT NULL DEFAULT 'contact',
  details TEXT NULL,
  status ENUM('new','read','replied','archived','spam') NOT NULL DEFAULT 'new',
  lang CHAR(2) NOT NULL DEFAULT 'de',
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  path VARCHAR(255) NOT NULL,
  thumb VARCHAR(255) NOT NULL DEFAULT '',
  original_name VARCHAR(255) NOT NULL DEFAULT '',
  mime VARCHAR(80) NOT NULL DEFAULT '',
  size INT UNSIGNED NOT NULL DEFAULT 0,
  width INT UNSIGNED NOT NULL DEFAULT 0,
  height INT UNSIGNED NOT NULL DEFAULT 0,
  alt VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_path (path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS visits (
  day DATE NOT NULL,
  path VARCHAR(190) NOT NULL,
  hits INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (day, path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_log (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NULL,
  username VARCHAR(60) NOT NULL DEFAULT '',
  action VARCHAR(40) NOT NULL,
  entity VARCHAR(60) NOT NULL DEFAULT '',
  entity_id VARCHAR(40) NOT NULL DEFAULT '',
  detail VARCHAR(255) NOT NULL DEFAULT '',
  ip_hash CHAR(16) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
